### ISSUE TITLE
AttributeError when accessing method from JWTAuth

### ISSUE THREAD

**Issue by sarise** [box/box-python-sdk#735]
Hi All,

I am unable to have JWTAuth working on my setup: python3.8, boxsdk 3.3.0, and Windows 11. My default Python 3.10, but that shouldn't matter because I am using a virtualenv.

```
(.venv) c:\Users\sari>pip freeze | findstr boxsdk
boxsdk==3.3.0

(.venv) c:\Users\sari>ipython
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from boxsdk import JWTAuth

In [2]: JWTAuth.from_settings_file
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 JWTAuth.from_settings_file

AttributeError: 'NoneType' object has no attribute 'from_settings_file'
```

I have been scratching my head over this error. The JWTAuth works fine on my python 3.10.
